name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to OCI Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.OCI_REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.OCI_REGISTRY }}/website:latest,${{ vars.OCI_REGISTRY }}/website:${{ github.sha }}
          cache-from: type=registry,ref=${{ vars.OCI_REGISTRY }}/website:buildcache
          cache-to: type=registry,ref=${{ vars.OCI_REGISTRY }}/website:buildcache,mode=max
