name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: git config --global init.defaultBranch main

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to OCI Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCI_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set environment variables
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "IMAGE_TAG_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build with Docker Compose
        run: |
          docker compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Push images
        run: |
         docker compose -f docker-compose.yml -f docker-compose.prod.yml push
  

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: git config --global init.defaultBranch main

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: 'true'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

      - name: Create remote directory
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "mkdir -p /srv/website"

      - name: Copy docker-compose files
        run: |
          scp docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/srv/website/
          scp docker-compose.prod.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/srv/website/

      - name: Deploy with docker-compose
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "cd /srv/website && docker compose -f docker-compose.yml -f docker-compose.prod.yml pull"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "cd /srv/website && docker compose -f docker-compose.yml -f docker-compose.prod.yml down"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "cd /srv/website && docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d"
